React & Redux group project - Space Travelers' Hub
jeanbuhendwa/react-group-project pull request #38
Opened 2023-04-13 20:17 UTC by jeanbuhendwa

## Space Travelers' Hub

#### In this pull request, we have : 

- [ ] Create React App.
- [ ] Installed [React Redux](https://react-redux.js.org/), [Redux Logger](https://www.npmjs.com/package/redux-logger) and [React Router](https://reactrouter.com/web/guides/quick-start).
- [ ] Downloaded the [free image](https://www.flaticon.com/free-icon/planet_3212567?term=space&page=1&position=19&page=1&position=19&related_id=3212567&origin=style) for the app logo.
- [ ] Created routes and view components: rockets, missions, my profile. 
- [ ] Used <NavLink /> for the page navigation links and style active class to indicate which section/page the user is currently on (underline active navigation link).
- [ ] Created directories for all Redux state slice files: rockets and missions
- [ ] used Rockets: `https://api.spacexdata.com/v4/rockets` and the Missions: `https://api.spacexdata.com/v3/missions`
- [ ] Used useSelector() Redux Hook to select the state slices and render lists of rockets and missions in corresponding routes.
- [ ] Wrote actions and reducers for cancelling rockets/dragons and leaving missions
- [ ] Rendered UI for rockets and missions

2023-04-13 22:23 UTC, algerina requested changes
Hi team,

Great job so far! 
However, you still have minor issues to fix.

May I highlight the following: 
- [x] Your project looks awesome👏  ✔️ 
- [x] Your PR is professional and well-detailed ✔️ 
- [x] I love the fact that you collaborated to a great extend as shown by the structure of the commits messages 👏  ✔️ 
- [x] It's a good  thing that you were able to get your linter checks to pass ✔️ 




## STATUS: CHANGES REQUIRED ♻️ 
PLEASE: check the comments under the review

<img src="https://media1.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

 
 ## Optional suggestions

 - Please check the comment under the review


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread and tag me @algerina if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)
___
_If anything seems to be unclear to you, reach out and ask anything by commenting on this Pull Request and mention me as [Algerina](https://github.com/algerina), I will receive a notification and will respond._

[GitHub](https://github.com/algerina) | [LinkedIn](https://linkedin.com/in/amel-khiri) | [Twitter](https://twitter.com/AmelQahwadji)

_Reviewed by [Amel Khiri ](https://github.com/algerina)_

2023-04-13 22:23 UTC, algerina commented on README.md
> +
- [ ]  It would be nice that we try to add a live demo link for the project 😉

2023-04-13 22:23 UTC, algerina commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
- [ ] The MIT license link is broken kindly work on that issue.

2023-04-14 05:57 UTC, alexander16108 commented
Hi @jeanbuhendwa @Patfarmurs , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media2.giphy.com/media/xnFN6mWrj7JGTqRj70/giphy-downsized-medium.gif"/>

## Highlights
 Your project looks awesome👏 ✔️
 Your PR is professional and well-detailed ✔️
 I love the fact that you collaborated to a great extend as shown by the structure of the commits messages 👏 ✔️
 It's a good thing that you were able to get your linter checks to pass ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-14 08:08 UTC, Patfarmurs commented
Thank you @alexander16108

2023-04-14 11:03 UTC, merged